import {
  Layout, Type, MousePointer2, Image, Square, AlignLeft, BoxSelect, CheckSquare, PlaySquare, ShieldAlert,
  CreditCard, User, Menu, Phone, Mail, MapPin, ArrowRight, Star, Check, X, ChevronDown, Facebook, Twitter, Instagram,
  Linkedin, Github, Search, ShoppingCart, Bell, Calendar, Clock, Eye, Heart, Share2, ThumbsUp, MessageCircle,
  AlertTriangle, Info, HelpCircle, Settings, LogOut, LogIn, ExternalLink, Download, Upload, Cloud, Database,
  Server, Activity, BarChart, PieChart, TrendingUp, DollarSign, Briefcase, Award, Gift, Zap, List
} from 'lucide-react';
import type { Block, CanvasNode, ElementType } from '@/types/editor';

const createNode = (type: ElementType, props = {}, style = {}, children: Partial<CanvasNode>[] = []): Partial<CanvasNode> => ({
  type,
  props,
  style,
  children: children as CanvasNode[]
});

export const BLOCKS: Block[] = [
  // --- HERO SECTIONS (8) ---
  { id: 'hero-centered', category: 'Hero', label: 'Hero Centered', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#ffffff', padding: '100px 20px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px' }, [createNode('badge', { content: 'New v2.0 Released' }, { backgroundColor: '#eff6ff', color: '#2563eb', padding: '6px 16px', borderRadius: '99px', fontSize: '14px', fontWeight: '500' }), createNode('h1', { content: 'Build Faster with Aether' }, { fontSize: '56px', fontWeight: '800', margin: '0', color: '#0f172a', lineHeight: '1.1' }), createNode('paragraph', { content: 'The ultimate low-code platform.' }, { fontSize: '20px', color: '#64748b', maxWidth: '700px' }), createNode('container', {}, { flexDirection: 'row', gap: '16px', justifyContent: 'center', border: 'none', padding: '0', backgroundColor: 'transparent' }, [createNode('button', { content: 'Get Started' }, { padding: '14px 28px', backgroundColor: '#2563eb', color: 'white', borderRadius: '8px' }), createNode('button', { content: 'View Demo' }, { padding: '14px 28px', backgroundColor: '#f1f5f9', color: '#334155', borderRadius: '8px' })])]) },
  { id: 'hero-split', category: 'Hero', label: 'Hero Split', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#f8fafc', padding: '80px 40px', display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '60px', alignItems: 'center' }, [createNode('container', {}, { border: 'none', padding: '0', backgroundColor: 'transparent', gap: '24px', alignItems: 'flex-start' }, [createNode('h1', { content: 'Design Without Limits' }, { fontSize: '48px', fontWeight: '800' }), createNode('paragraph', { content: 'Create stunning websites visually.' }, { fontSize: '18px', color: '#64748b' }), createNode('button', { content: 'Start Building' }, { padding: '14px 32px', backgroundColor: '#0f172a', color: 'white', borderRadius: '8px' })]), createNode('image', { src: 'https://placehold.co/600x400' }, { borderRadius: '16px' })]) },
  { id: 'hero-dark', category: 'Hero', label: 'Hero Dark', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#0f172a', padding: '100px 20px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '24px' }, [createNode('h1', { content: 'Ship Products Faster' }, { fontSize: '56px', fontWeight: '800', color: '#ffffff' }), createNode('paragraph', { content: 'Stop wrestling with code.' }, { fontSize: '20px', color: '#94a3b8' }), createNode('button', { content: 'Start Free Trial' }, { padding: '14px 28px', backgroundColor: '#3b82f6', color: 'white', borderRadius: '8px' })]) },
  { id: 'hero-video', category: 'Hero', label: 'Hero Video', icon: PlaySquare, elements: createNode('section', {}, { backgroundColor: '#000', padding: '120px 20px', textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: '600px' }, [createNode('h1', { content: 'Immersive Experiences' }, { fontSize: '64px', fontWeight: '900', color: 'white' }), createNode('paragraph', { content: 'Captivate your audience.' }, { fontSize: '24px', color: '#e2e8f0' }), createNode('button', { content: 'Watch Reel' }, { padding: '16px 32px', backgroundColor: 'white', color: 'black', borderRadius: '99px' })]) },
  { id: 'hero-app', category: 'Hero', label: 'Hero App', icon: Layout, elements: createNode('section', {}, { padding: '60px 20px', backgroundColor: '#fff', alignItems: 'center', display: 'flex', flexDirection: 'column' }, [createNode('h1', { content: 'The App for Everything' }, { fontSize: '48px', fontWeight: 'bold' }), createNode('image', { src: 'https://placehold.co/300x600?text=Mobile+App' }, { borderRadius: '24px', border: '8px solid #000', marginTop: '40px' })]) },
  { id: 'hero-minimal', category: 'Hero', label: 'Hero Minimal', icon: Layout, elements: createNode('section', {}, { padding: '120px 20px', backgroundColor: '#fff', textAlign: 'left' }, [createNode('h1', { content: 'Less is More.' }, { fontSize: '80px', fontWeight: '900', lineHeight: '1' }), createNode('paragraph', { content: 'Minimalist design for maximum impact.' }, { fontSize: '24px', color: '#666', marginTop: '20px' })]) },
  { id: 'hero-saas', category: 'Hero', label: 'Hero SaaS', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#f0f9ff', padding: '80px 20px', textAlign: 'center' }, [createNode('h1', { content: 'Manage your SaaS' }, { fontSize: '48px', fontWeight: 'bold' }), createNode('container', {}, { padding: '20px', backgroundColor: 'white', borderRadius: '8px', marginTop: '40px', boxShadow: '0 10px 20px rgba(0,0,0,0.1)' }, [createNode('paragraph', { content: 'Dashboard Placeholder' }, {})])]) },
  { id: 'hero-gradient', category: 'Hero', label: 'Hero Gradient', icon: Layout, elements: createNode('section', {}, { background: 'linear-gradient(to right, #4facfe 0%, #00f2fe 100%)', padding: '100px 20px', textAlign: 'center' }, [createNode('h1', { content: 'Vibrant Colors' }, { fontSize: '56px', fontWeight: 'bold', color: 'white' }), createNode('paragraph', { content: 'Stand out from the crowd.' }, { color: 'white', fontSize: '20px' })]) },

  // --- FEATURES (6) ---
  { id: 'feat-3', category: 'Features', label: 'Features 3-Col', icon: Square, elements: createNode('section', {}, { padding: '80px 20px' }, [createNode('h2', { content: 'Key Features' }, { textAlign: 'center', fontSize: '32px' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '30px' }, [createNode('card', {}, { padding: '20px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Fast' }, {}), createNode('paragraph', { content: 'Blazing fast performance.' }, {})]), createNode('card', {}, { padding: '20px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Secure' }, {}), createNode('paragraph', { content: 'Top-notch security.' }, {})]), createNode('card', {}, { padding: '20px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Reliable' }, {}), createNode('paragraph', { content: '99.9% uptime.' }, {})])])]) },
  { id: 'feat-left', category: 'Features', label: 'Feature Left', icon: Layout, elements: createNode('section', {}, { padding: '60px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' }, [createNode('image', { src: 'https://placehold.co/400x300' }, { borderRadius: '8px' }), createNode('container', {}, { justifyContent: 'center' }, [createNode('h2', { content: 'Visual Editor' }, { fontSize: '32px' }), createNode('paragraph', { content: 'Edit everything visually.' }, {})])]) },
  { id: 'feat-right', category: 'Features', label: 'Feature Right', icon: Layout, elements: createNode('section', {}, { padding: '60px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '40px' }, [createNode('container', {}, { justifyContent: 'center' }, [createNode('h2', { content: 'Code Export' }, { fontSize: '32px' }), createNode('paragraph', { content: 'Get clean HTML/CSS.' }, {})]), createNode('image', { src: 'https://placehold.co/400x300' }, { borderRadius: '8px' })]) },
  { id: 'feat-cards-4', category: 'Features', label: 'Features 4-Col', icon: Square, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px' }, [createNode('card', {}, { padding: '15px', border: '1px solid #eee' }, [createNode('h4', { content: 'Feature 1' }, {})]), createNode('card', {}, { padding: '15px', border: '1px solid #eee' }, [createNode('h4', { content: 'Feature 2' }, {})]), createNode('card', {}, { padding: '15px', border: '1px solid #eee' }, [createNode('h4', { content: 'Feature 3' }, {})]), createNode('card', {}, { padding: '15px', border: '1px solid #eee' }, [createNode('h4', { content: 'Feature 4' }, {})])])]) },
  { id: 'feat-list', category: 'Features', label: 'Feature List', icon: List, elements: createNode('section', {}, { padding: '60px 20px', maxWidth: '800px', margin: '0 auto' }, [createNode('h2', { content: 'Why choose us?' }, { textAlign: 'center' }), createNode('container', {}, { gap: '10px' }, [createNode('card', {}, { padding: '15px', border: '1px solid #eee', flexDirection: 'row', alignItems: 'center', gap: '10px' }, [createNode('badge', { content: '1' }, {}), createNode('h4', { content: 'Reason One' }, {})]), createNode('card', {}, { padding: '15px', border: '1px solid #eee', flexDirection: 'row', alignItems: 'center', gap: '10px' }, [createNode('badge', { content: '2' }, {}), createNode('h4', { content: 'Reason Two' }, {})]), createNode('card', {}, { padding: '15px', border: '1px solid #eee', flexDirection: 'row', alignItems: 'center', gap: '10px' }, [createNode('badge', { content: '3' }, {}), createNode('h4', { content: 'Reason Three' }, {})])])]) },
  { id: 'feat-dark', category: 'Features', label: 'Features Dark', icon: Square, elements: createNode('section', {}, { padding: '80px 20px', backgroundColor: '#111', color: 'white' }, [createNode('h2', { content: 'Dark Mode Features' }, { textAlign: 'center' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '30px' }, [createNode('card', {}, { padding: '20px', backgroundColor: '#222' }, [createNode('h3', { content: 'Sleek' }, {})]), createNode('card', {}, { padding: '20px', backgroundColor: '#222' }, [createNode('h3', { content: 'Modern' }, {})]), createNode('card', {}, { padding: '20px', backgroundColor: '#222' }, [createNode('h3', { content: 'Fast' }, {})])])]) },

  // --- PRICING (4) ---
  { id: 'pricing-basic', category: 'Pricing', label: 'Pricing Basic', icon: CreditCard, elements: createNode('section', {}, { padding: '80px 20px' }, [createNode('h2', { content: 'Pricing' }, { textAlign: 'center' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px' }, [createNode('card', {}, { padding: '30px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Free' }, {}), createNode('h1', { content: '$0' }, {})]), createNode('card', {}, { padding: '30px', border: '2px solid blue' }, [createNode('h3', { content: 'Pro' }, {}), createNode('h1', { content: '$29' }, {})]), createNode('card', {}, { padding: '30px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Biz' }, {}), createNode('h1', { content: '$99' }, {})])])]) },
  { id: 'pricing-dark-p', category: 'Pricing', label: 'Pricing Dark', icon: CreditCard, elements: createNode('section', {}, { padding: '80px 20px', backgroundColor: '#1a1a1a', color: 'white' }, [createNode('h2', { content: 'Plans' }, { textAlign: 'center' }), createNode('container', {}, { justifyContent: 'center', flexDirection: 'row' }, [createNode('card', {}, { padding: '40px', backgroundColor: '#333', width: '300px' }, [createNode('h3', { content: 'Premium' }, {}), createNode('h1', { content: '$49' }, {})])])]) },
  { id: 'pricing-table', category: 'Pricing', label: 'Pricing Table', icon: CreditCard, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { width: '100%', border: '1px solid #eee' }, [createNode('grid-row', {}, {}, [createNode('grid-col', {}, {}, [createNode('h4', { content: 'Feature' }, {})]), createNode('grid-col', {}, {}, [createNode('h4', { content: 'Basic' }, {})]), createNode('grid-col', {}, {}, [createNode('h4', { content: 'Pro' }, {})])]), createNode('divider', {}, {}), createNode('grid-row', {}, {}, [createNode('grid-col', {}, {}, [createNode('paragraph', { content: 'Users' }, {})]), createNode('grid-col', {}, {}, [createNode('paragraph', { content: '1' }, {})]), createNode('grid-col', {}, {}, [createNode('paragraph', { content: 'Unlimited' }, {})])])])]) },
  { id: 'pricing-cards-2', category: 'Pricing', label: 'Pricing 2-Col', icon: CreditCard, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px' }, [createNode('card', {}, { padding: '30px', border: '1px solid #ddd' }, [createNode('h3', { content: 'Monthly' }, {}), createNode('h1', { content: '$19' }, {})]), createNode('card', {}, { padding: '30px', border: '1px solid #ddd', backgroundColor: '#f0f9ff' }, [createNode('h3', { content: 'Yearly' }, {}), createNode('h1', { content: '$190' }, {})])])]) },

  // --- TESTIMONIALS (3) ---
  { id: 'test-grid', category: 'Testimonials', label: 'Testimonials Grid', icon: MessageCircle, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('h2', { content: 'Reviews' }, { textAlign: 'center' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '20px', marginTop: '30px' }, [createNode('card', {}, { padding: '20px', backgroundColor: '#f9f9f9' }, [createNode('blockquote', { content: '"Great Tool!"' }, {}), createNode('label', { content: '- User A' }, {})]), createNode('card', {}, { padding: '20px', backgroundColor: '#f9f9f9' }, [createNode('blockquote', { content: '"Amazing Support"' }, {}), createNode('label', { content: '- User B' }, {})]), createNode('card', {}, { padding: '20px', backgroundColor: '#f9f9f9' }, [createNode('blockquote', { content: '"Loved it"' }, {}), createNode('label', { content: '- User C' }, {})])])]) },
  { id: 'test-single', category: 'Testimonials', label: 'Testimonial Large', icon: MessageCircle, elements: createNode('section', {}, { padding: '80px 20px', backgroundColor: '#111', color: 'white', textAlign: 'center' }, [createNode('blockquote', { content: '"This is the best product I have ever used."' }, { fontSize: '24px', fontStyle: 'italic' }), createNode('avatar', { src: 'https://i.pravatar.cc/150' }, { margin: '20px auto' }), createNode('label', { content: 'Jane Doe, CEO' }, {})]) },
  { id: 'test-cards-2', category: 'Testimonials', label: 'Testimonials 2-Col', icon: MessageCircle, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }, [createNode('card', {}, { padding: '20px', border: '1px solid #eee' }, [createNode('blockquote', { content: '"Good value"' }, {})]), createNode('card', {}, { padding: '20px', border: '1px solid #eee' }, [createNode('blockquote', { content: '"Highly recommend"' }, {})])])]) },

  // --- CTA (4) ---
  { id: 'cta-simple', category: 'CTA', label: 'CTA Simple', icon: Zap, elements: createNode('section', {}, { padding: '80px 20px', backgroundColor: '#2563eb', color: 'white', textAlign: 'center' }, [createNode('h2', { content: 'Ready to start?' }, { fontSize: '36px' }), createNode('button', { content: 'Get Started' }, { backgroundColor: 'white', color: 'blue', padding: '12px 24px', borderRadius: '4px', marginTop: '20px' })]) },
  { id: 'cta-split', category: 'CTA', label: 'CTA Split', icon: Zap, elements: createNode('section', {}, { padding: '60px 20px', backgroundColor: '#f1f5f9', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }, [createNode('h2', { content: 'Join usage today' }, {}), createNode('button', { content: 'Sign Up' }, { backgroundColor: 'black', color: 'white', padding: '10px 20px', borderRadius: '4px' })]) },
  { id: 'cta-image', category: 'CTA', label: 'CTA Image', icon: Zap, elements: createNode('section', {}, { padding: '0', display: 'grid', gridTemplateColumns: '1fr 1fr', height: '400px' }, [createNode('container', {}, { backgroundColor: '#333', color: 'white', justifyContent: 'center', padding: '40px' }, [createNode('h2', { content: 'Join Us' }, {}), createNode('button', { content: 'Register' }, { backgroundColor: 'white', color: 'black', padding: '10px' })]), createNode('image', { src: 'https://placehold.co/600x400' }, { height: '100%', objectFit: 'cover' })]) },
  { id: 'cta-card', category: 'CTA', label: 'CTA Boxed', icon: Zap, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('card', {}, { backgroundColor: '#000', color: '#fff', padding: '40px', borderRadius: '16px', textAlign: 'center' }, [createNode('h2', { content: 'Get 50% Off' }, {}), createNode('button', { content: 'Claim Offer' }, { backgroundColor: '#fff', color: '#000', padding: '10px 20px', borderRadius: '99px', marginTop: '20px' })])]) },

  // --- TEAM (3) ---
  { id: 'team-grid', category: 'Team', label: 'Team Grid', icon: User, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('h2', { content: 'Our Team' }, { textAlign: 'center' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px', marginTop: '30px' }, [createNode('card', {}, { alignItems: 'center' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=1' }, {}), createNode('label', { content: 'Member 1' }, {})]), createNode('card', {}, { alignItems: 'center' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=2' }, {}), createNode('label', { content: 'Member 2' }, {})]), createNode('card', {}, { alignItems: 'center' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=3' }, {}), createNode('label', { content: 'Member 3' }, {})]), createNode('card', {}, { alignItems: 'center' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=4' }, {}), createNode('label', { content: 'Member 4' }, {})])])]) },
  { id: 'team-circles', category: 'Team', label: 'Team Circles', icon: User, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { flexDirection: 'row', justifyContent: 'center', gap: '30px' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=5' }, { width: '100px', height: '100px' }), createNode('avatar', { src: 'https://i.pravatar.cc/150?u=6' }, { width: '100px', height: '100px' }), createNode('avatar', { src: 'https://i.pravatar.cc/150?u=7' }, { width: '100px', height: '100px' })])]) },
  { id: 'team-list', category: 'Team', label: 'Team List', icon: User, elements: createNode('section', {}, { padding: '60px 20px', maxWidth: '600px', margin: '0 auto' }, [createNode('card', {}, { flexDirection: 'row', alignItems: 'center', gap: '20px', padding: '10px', marginBottom: '10px' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=8' }, {}), createNode('container', {}, {}, [createNode('h4', { content: 'Leader' }, {}), createNode('paragraph', { content: 'CEO' }, {})])]), createNode('card', {}, { flexDirection: 'row', alignItems: 'center', gap: '20px', padding: '10px' }, [createNode('avatar', { src: 'https://i.pravatar.cc/150?u=9' }, {}), createNode('container', {}, {}, [createNode('h4', { content: 'Manager' }, {}), createNode('paragraph', { content: 'CTO' }, {})])])]) },

  // --- NAVIGATION (2) ---
  { id: 'nav-simple', category: 'Navigation', label: 'Nav Simple', icon: Menu, elements: createNode('section', {}, { borderBottom: '1px solid #eee', padding: '15px 40px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', backgroundColor: '#fff' }, [createNode('h3', { content: 'Brand' }, {}), createNode('container', {}, { flexDirection: 'row', gap: '20px' }, [createNode('link', { content: 'Home' }, {}), createNode('link', { content: 'About' }, {})])]) },
  { id: 'nav-center', category: 'Navigation', label: 'Nav Centered', icon: Menu, elements: createNode('section', {}, { borderBottom: '1px solid #eee', padding: '15px 40px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', backgroundColor: '#fff' }, [createNode('h3', { content: 'Brand' }, {}), createNode('container', {}, { flexDirection: 'row', gap: '30px' }, [createNode('link', { content: 'Link 1' }, {}), createNode('link', { content: 'Link 2' }, {}), createNode('link', { content: 'Link 3' }, {})])]) },

  // --- FOOTERS (3) ---
  { id: 'foot-simple', category: 'Footer', label: 'Footer Simple', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#f9f9f9', padding: '40px', textAlign: 'center' }, [createNode('paragraph', { content: '© 2024 Company. All rights reserved.' }, {})]) },
  { id: 'foot-cols', category: 'Footer', label: 'Footer Cols', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#000', color: '#fff', padding: '60px 20px', display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)' }, [createNode('container', {}, {}, [createNode('h4', { content: 'Col 1' }, {}), createNode('link', { content: 'Link' }, { color: '#888' })]), createNode('container', {}, {}, [createNode('h4', { content: 'Col 2' }, {}), createNode('link', { content: 'Link' }, { color: '#888' })]), createNode('container', {}, {}, [createNode('h4', { content: 'Col 3' }, {}), createNode('link', { content: 'Link' }, { color: '#888' })]), createNode('container', {}, {}, [createNode('h4', { content: 'Col 4' }, {}), createNode('link', { content: 'Link' }, { color: '#888' })])]) },
  { id: 'foot-social', category: 'Footer', label: 'Footer Social', icon: Layout, elements: createNode('section', {}, { backgroundColor: '#111', padding: '40px', color: '#fff', textAlign: 'center' }, [createNode('h3', { content: 'Follow Us' }, {}), createNode('container', {}, { flexDirection: 'row', justifyContent: 'center', gap: '20px', marginTop: '10px' }, [createNode('badge', { content: 'FB' }, {}), createNode('badge', { content: 'TW' }, {}), createNode('badge', { content: 'IG' }, {})])]) },

  // --- FORMS (3) ---
  { id: 'form-contact', category: 'Forms', label: 'Contact Form', icon: Mail, elements: createNode('section', {}, { padding: '60px 20px', maxWidth: '500px', margin: '0 auto' }, [createNode('label', { content: 'Name' }, {}), createNode('input', { placeholder: 'Name' }, { marginBottom: '10px' }), createNode('label', { content: 'Email' }, {}), createNode('input', { placeholder: 'Email' }, { marginBottom: '10px' }), createNode('button', { content: 'Send' }, { backgroundColor: 'blue', color: 'white', padding: '10px', width: '100%' })]) },
  { id: 'form-login', category: 'Forms', label: 'Login Form', icon: LogIn, elements: createNode('section', {}, { padding: '100px 20px', display: 'flex', justifyContent: 'center' }, [createNode('card', {}, { padding: '40px', width: '300px', border: '1px solid #ccc' }, [createNode('h2', { content: 'Login' }, { textAlign: 'center' }), createNode('input', { placeholder: 'Email' }, { margin: '10px 0' }), createNode('input', { placeholder: 'Password', type: 'password' }, { margin: '10px 0' }), createNode('button', { content: 'Login' }, { width: '100%', backgroundColor: 'black', color: 'white', padding: '10px' })])]) },
  { id: 'form-news', category: 'Forms', label: 'Newsletter', icon: Mail, elements: createNode('section', {}, { padding: '60px 20px', backgroundColor: '#eee', textAlign: 'center' }, [createNode('h2', { content: 'Subscribe' }, {}), createNode('container', {}, { flexDirection: 'row', justifyContent: 'center', gap: '10px', marginTop: '20px' }, [createNode('input', { placeholder: 'Email' }, {}), createNode('button', { content: 'Join' }, { backgroundColor: 'blue', color: 'white' })])]) },

  // --- MEDIA (3) ---
  { id: 'gallery-grid', category: 'Media', label: 'Gallery Grid', icon: Image, elements: createNode('section', {}, { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '10px', padding: '20px' }, [createNode('image', { src: 'https://placehold.co/300x300' }, {}), createNode('image', { src: 'https://placehold.co/300x300' }, {}), createNode('image', { src: 'https://placehold.co/300x300' }, {}), createNode('image', { src: 'https://placehold.co/300x300' }, {}), createNode('image', { src: 'https://placehold.co/300x300' }, {}), createNode('image', { src: 'https://placehold.co/300x300' }, {})]) },
  { id: 'media-video', category: 'Media', label: 'Video Embed', icon: PlaySquare, elements: createNode('section', {}, { padding: '40px' }, [createNode('video', { src: 'https://www.youtube.com/embed/dQw4w9WgXcQ' }, {})]) },
  { id: 'logo-cloud', category: 'Media', label: 'Logo Cloud', icon: Image, elements: createNode('section', {}, { padding: '40px', textAlign: 'center' }, [createNode('paragraph', { content: 'Trusted by:' }, { color: '#888' }), createNode('container', {}, { flexDirection: 'row', justifyContent: 'center', gap: '30px', marginTop: '10px', fontSize: '24px', fontWeight: 'bold', color: '#ccc' }, [createNode('label', { content: 'LOGO 1' }, {}), createNode('label', { content: 'LOGO 2' }, {}), createNode('label', { content: 'LOGO 3' }, {})])]) },

  // --- FAQ (2) ---
  { id: 'faq-list', category: 'Features', label: 'FAQ Simple', icon: HelpCircle, elements: createNode('section', {}, { padding: '60px 20px', maxWidth: '800px', margin: '0 auto' }, [createNode('h2', { content: 'FAQ' }, { textAlign: 'center' }), createNode('card', {}, { padding: '20px', margin: '10px 0', border: '1px solid #eee' }, [createNode('h4', { content: 'Question 1?' }, {}), createNode('paragraph', { content: 'Answer 1.' }, { color: '#666' })]), createNode('card', {}, { padding: '20px', margin: '10px 0', border: '1px solid #eee' }, [createNode('h4', { content: 'Question 2?' }, {}), createNode('paragraph', { content: 'Answer 2.' }, { color: '#666' })])]) },
  { id: 'faq-grid', category: 'Features', label: 'FAQ Grid', icon: HelpCircle, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('h2', { content: 'Common Questions' }, { textAlign: 'center' }), createNode('container', {}, { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px', marginTop: '30px' }, [createNode('card', {}, { padding: '20px', backgroundColor: '#f9f9f9' }, [createNode('h4', { content: 'Q1' }, {}), createNode('paragraph', { content: 'A1' }, {})]), createNode('card', {}, { padding: '20px', backgroundColor: '#f9f9f9' }, [createNode('h4', { content: 'Q2' }, {}), createNode('paragraph', { content: 'A2' }, {})])])]) },

  // --- STATS (2) ---
  { id: 'stats-bar', category: 'Features', label: 'Stats Bar', icon: BarChart, elements: createNode('section', {}, { padding: '60px 20px', backgroundColor: '#2563eb', color: 'white' }, [createNode('container', {}, { flexDirection: 'row', justifyContent: 'space-around', textAlign: 'center' }, [createNode('container', {}, {}, [createNode('h1', { content: '1M+' }, {}), createNode('paragraph', { content: 'Users' }, {})]), createNode('container', {}, {}, [createNode('h1', { content: '500+' }, {}), createNode('paragraph', { content: 'Clients' }, {})]), createNode('container', {}, {}, [createNode('h1', { content: '100%' }, {}), createNode('paragraph', { content: 'Satisfaction' }, {})])])]) },
  { id: 'stats-cards', category: 'Features', label: 'Stats Cards', icon: BarChart, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: '20px' }, [createNode('card', {}, { padding: '20px', border: '1px solid #ddd', textAlign: 'center' }, [createNode('h2', { content: '30%' }, { color: 'green' }), createNode('paragraph', { content: 'Growth' }, {})]), createNode('card', {}, { padding: '20px', border: '1px solid #ddd', textAlign: 'center' }, [createNode('h2', { content: '40%' }, { color: 'blue' }), createNode('paragraph', { content: 'Speed' }, {})])])]) },

  // --- HEADER/PAGE TITLE (3) ---
  { id: 'header-simple', category: 'Header', label: 'Page Header', icon: Type, elements: createNode('section', {}, { padding: '40px 20px', backgroundColor: '#f4f4f5' }, [createNode('h1', { content: 'Page Title' }, { fontSize: '32px' }), createNode('paragraph', { content: 'Breadcrumb / Link' }, {})]) },
  { id: 'header-center', category: 'Header', label: 'Header Center', icon: Type, elements: createNode('section', {}, { padding: '60px 20px', textAlign: 'center', backgroundColor: '#fff' }, [createNode('h1', { content: 'Big Title' }, { fontSize: '48px' }), createNode('paragraph', { content: 'Subtitle goes here.' }, { fontSize: '20px', color: '#666' })]) },
  { id: 'header-image', category: 'Header', label: 'Header Image', icon: Type, elements: createNode('section', {}, { height: '300px', backgroundImage: 'url(https://placehold.co/1200x300)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'white' }, [createNode('h1', { content: 'Image Header' }, { textShadow: '0 2px 4px rgba(0,0,0,0.5)' })]) },

  // --- CONTENT (4) ---
  { id: 'content-text', category: 'Content', label: 'Text Block', icon: AlignLeft, elements: createNode('section', {}, { padding: '40px 20px', maxWidth: '800px', margin: '0 auto' }, [createNode('h2', { content: 'Article Title' }, {}), createNode('paragraph', { content: 'Lorem ipsum dolor sit amet.' }, {}), createNode('paragraph', { content: 'Consectetur adipiscing elit.' }, {})]) },
  { id: 'content-cols', category: 'Content', label: '2-Col Text', icon: AlignLeft, elements: createNode('section', {}, { padding: '40px 20px', display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px' }, [createNode('paragraph', { content: 'Left column content.' }, {}), createNode('paragraph', { content: 'Right column content.' }, {})]) },
  { id: 'content-quote', category: 'Content', label: 'Quote Block', icon: AlignLeft, elements: createNode('section', {}, { padding: '60px 20px', backgroundColor: '#fff' }, [createNode('blockquote', { content: '"Design is intelligence made visible."' }, { borderLeft: '4px solid black', paddingLeft: '20px', fontSize: '24px' })]) },
  { id: 'content-list', category: 'Content', label: 'Checklist', icon: CheckSquare, elements: createNode('section', {}, { padding: '40px 20px' }, [createNode('container', {}, { gap: '10px' }, [createNode('paragraph', { content: '✅ Item one' }, {}), createNode('paragraph', { content: '✅ Item two' }, {}), createNode('paragraph', { content: '✅ Item three' }, {})])]) },

  // --- STEPS (2) ---
  { id: 'steps-h', category: 'Features', label: 'Steps Horiz', icon: List, elements: createNode('section', {}, { padding: '60px 20px' }, [createNode('container', {}, { flexDirection: 'row', justifyContent: 'space-between' }, [createNode('card', {}, { width: '30%', textAlign: 'center' }, [createNode('badge', { content: '1' }, {}), createNode('h4', { content: 'Step 1' }, {})]), createNode('card', {}, { width: '30%', textAlign: 'center' }, [createNode('badge', { content: '2' }, {}), createNode('h4', { content: 'Step 2' }, {})]), createNode('card', {}, { width: '30%', textAlign: 'center' }, [createNode('badge', { content: '3' }, {}), createNode('h4', { content: 'Step 3' }, {})])])]) },
  { id: 'steps-v', category: 'Features', label: 'Steps Vert', icon: List, elements: createNode('section', {}, { padding: '60px 20px', maxWidth: '600px' }, [createNode('container', {}, { gap: '20px', borderLeft: '2px solid #ddd', paddingLeft: '20px' }, [createNode('container', {}, {}, [createNode('h4', { content: 'Step 1' }, {}), createNode('paragraph', { content: 'Details...' }, {})]), createNode('container', {}, {}, [createNode('h4', { content: 'Step 2' }, {}), createNode('paragraph', { content: 'Details...' }, {})]), createNode('container', {}, {}, [createNode('h4', { content: 'Step 3' }, {}), createNode('paragraph', { content: 'Details...' }, {})])])]) },

  // --- UTILITY (3) ---
  { id: '404-page', category: 'Utility', label: '404 Page', icon: AlertTriangle, elements: createNode('section', {}, { height: '80vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center' }, [createNode('h1', { content: '404' }, { fontSize: '96px', color: '#ccc' }), createNode('h2', { content: 'Page Not Found' }, {}), createNode('button', { content: 'Go Home' }, { backgroundColor: 'blue', color: 'white', padding: '10px 20px', marginTop: '20px' })]) },
  { id: 'sidebar', category: 'Utility', label: 'Sidebar', icon: Layout, elements: createNode('grid-col', {}, { width: '250px', height: '100%', backgroundColor: '#f4f4f5', padding: '20px', gap: '10px' }, [createNode('h3', { content: 'Menu' }, {}), createNode('link', { content: 'Dashboard' }, {}), createNode('link', { content: 'Settings' }, {}), createNode('link', { content: 'Profile' }, {})]) },
  { id: 'breadcrumbs', category: 'Utility', label: 'Breadcrumbs', icon: Layout, elements: createNode('container', {}, { flexDirection: 'row', gap: '10px', fontSize: '14px', color: '#666' }, [createNode('link', { content: 'Home' }, {}), createNode('paragraph', { content: '/' }, {}), createNode('link', { content: 'Category' }, {}), createNode('paragraph', { content: '/' }, {}), createNode('paragraph', { content: 'Current' }, { fontWeight: 'bold' })]) }
];
